import React from "react";
import { createStyles, makeStyles, Theme } from "@material-ui/core/styles";
import GridList from "@material-ui/core/GridList";
import BusinessCard from "./BusinessCard";

interface Props {
  filterValue: string;
}

const useStyles = makeStyles((theme: Theme) =>
  createStyles({
    root: {
      display: "flex",
      flexWrap: "wrap",
      justifyContent: "space-around",
      overflow: "hidden",
      backgroundColor: "#9AC7BF",
      width: "100%",
      height: "auto",
    },
    gridList: {
      width: 500,
      height: 450,
      transform: "translateZ(0)",
    },
    gridListTile: {
      width: "100%",
      height: "3rem",
    },
  })
);

const AllBusiness: React.FC<Props> = ({ filterValue }) => {
  const businesses = [
    {
      name: "Provigo",
      rating: 4,
      count: 321,
      location: "3421 Avenue du Parc, Montreal, QC H2X 2H6",
      type: "supermarket",
      business_id: 1,
      local: false,
      ratingSanitizer: 4,
      ratingSocialDistancing: 3,
      ratingLimitingCustomers: 5,
      ratingMasks: 4,
      ratingAccomodation: 3,
    },
    {
      name: "Provigo",
      rating: 3,
      count: 259,
      location: "50 Avenue du Mont-Royal O, Montreal, QC H2T 2S3",
      type: "supermarket",
      business_id: 2,
      local: false,
      ratingSanitizer: 2,
      ratingSocialDistancing: 3,
      ratingLimitingCustomers: 4,
      ratingMasks: 4,
      ratingAccomodation: 3,
    },
    {
      name: "Provigo",
      rating: 4,
      count: 284,
      location:
        "1275 Avenue des Canadiens-de-Montréal #200, Montréal, QC H3B 5E8",
      type: "supermarket",
      business_id: 3,
      local: false,
      ratingSanitizer: 4,
      ratingSocialDistancing: 5,
      ratingLimitingCustomers: 4,
      ratingMasks: 4,
      ratingAccomodation: 3,
    },
    {
      name: "Metro",
      rating: 4,
      count: 159,
      location: "3575 Park Avenue Suite 5100, Montreal, QC H2X 3P9",
      type: "supermarket",
      business_id: 4,
      local: false,
      ratingSanitizer: 4,
      ratingSocialDistancing: 2,
      ratingLimitingCustomers: 4,
      ratingMasks: 2,
      ratingAccomodation: 4,
    },
    {
      name: "Epicerie Segal",
      rating: 2,
      count: 273,
      location: "4001 Boulevard Saint-Laurent, Montreal, QC H2W 1Y4",
      type: "supermarket",
      business_id: 5,
      local: true,
      ratingSanitizer: 3,
      ratingSocialDistancing: 4,
      ratingLimitingCustomers: 3,
      ratingMasks: 2,
      ratingAccomodation: 2,
    },
    {
      name: "La Banquise",
      rating: 4,
      count: 259,
      location: "994 Rue Rachel E, Montreal, QC H2J 2J3",
      type: "restaurant",
      business_id: 6,
      local: true,
      ratingSanitizer: 4,
      ratingSocialDistancing: 3,
      ratingLimitingCustomers: 5,
      ratingMasks: 4,
      ratingAccomodation: 3,
    },
    {
      name: "A&W",
      rating: 2,
      count: 109,
      location: "3780 Boulevard Saint-Laurent, Montreal, QC H2W 1X6",
      type: "restaurant",
      business_id: 7,
      local: false,
      ratingSanitizer: 4,
      ratingSocialDistancing: 2,
      ratingLimitingCustomers: 3,
      ratingMasks: 4,
      ratingAccomodation: 4,
    },
    {
      name: "A&W",
      rating: 3,
      count: 95,
      location: "3457 Avenue du Parc, Montreal, QC H2X 2H6",
      type: "restaurant",
      business_id: 8,
      local: false,
      ratingSanitizer: 2,
      ratingSocialDistancing: 3,
      ratingLimitingCustomers: 4,
      ratingMasks: 1,
      ratingAccomodation: 4,
    },
    {
      name: "3 Brasseurs",
      rating: 5,
      count: 193,
      location: "1658 Rue Saint-Denis, Montreal, QC H2X 3K4",
      type: "restaurant",
      business_id: 9,
      local: false,
      ratingSanitizer: 2,
      ratingSocialDistancing: 3,
      ratingLimitingCustomers: 4,
      ratingMasks: 2,
      ratingAccomodation: 5,
    },
    {
      name: "McDonald's",
      rating: 1,
      count: 108,
      location: "1647 Rue Saint-Denis, Montreal, QC H2X 3K4",
      type: "restaurant",
      business_id: 10,
      local: false,
      ratingSanitizer: 1,
      ratingSocialDistancing: 2,
      ratingLimitingCustomers: 1,
      ratingMasks: 2,
      ratingAccomodation: 1,
    },
    {
      name: "Pizza Pizza",
      rating: 2,
      count: 83,
      location: "3714 Boulevard Saint-Laurent, Montreal, QC H2X 1A1",
      type: "restaurant",
      business_id: 11,
      local: false,
      ratingSanitizer: 1,
      ratingSocialDistancing: 2,
      ratingLimitingCustomers: 3,
      ratingMasks: 3,
      ratingAccomodation: 4,
    },
    {
      name: "Decathlon",
      rating: 5,
      count: 157,
      location: "705 Rue Saint-Catherine O #3500, Montreal, QC H3B 4G5",
      type: "sport store",
      business_id: 12,
      local: false,
      ratingSanitizer: 5,
      ratingSocialDistancing: 4,
      ratingLimitingCustomers: 4,
      ratingMasks: 5,
      ratingAccomodation: 4,
    },
    {
      name: "Gap",
      rating: 3,
      count: 96,
      location: "705 Rue Saint-Catherine O #3123, Montreal, QC H3B 4G5",
      type: "clothing store",
      business_id: 13,
      local: false,
      ratingSanitizer: 2,
      ratingSocialDistancing: 4,
      ratingLimitingCustomers: 2,
      ratingMasks: 3,
      ratingAccomodation: 5,
    },
    {
      name: "H&M",
      rating: 4,
      count: 112,
      location: "1100 Rue Saint-Catherine O, Montreal, QC H3B 1H4",
      type: "clothing store",
      business_id: 14,
      local: false,
      ratingSanitizer: 4,
      ratingSocialDistancing: 4,
      ratingLimitingCustomers: 3,
      ratingMasks: 3,
      ratingAccomodation: 2,
    },
    {
      name: "Sports Experts",
      rating: 3,
      count: 75,
      location: "930 Rue Saint-Catherine O, Montreal, QCH3B 1E2",
      type: "sport store",
      business_id: 15,
      local: false,
      ratingSanitizer: 4,
      ratingSocialDistancing: 4,
      ratingLimitingCustomers: 3,
      ratingMasks: 3,
      ratingAccomodation: 2,
    },
    {
      name: "Bagels St-Viateur",
      rating: 4,
      count: 231,
      location: "263 Rue Saint-Viateur O, Montreal, QC H2V 1Y1",
      type: "cafe",
      business_id: 16,
      local: true,
      ratingSanitizer: 1,
      ratingSocialDistancing: 4,
      ratingLimitingCustomers: 3,
      ratingMasks: 2,
      ratingAccomodation: 4,
    },
    {
      name: "Fairmount Bagel",
      rating: 5,
      count: 146,
      location: "74 Avenue Fairmount O, Montreal, QC H2T 2M2",
      type: "cafe",
      business_id: 17,
      local: true,
      ratingSanitizer: 4,
      ratingSocialDistancing: 2,
      ratingLimitingCustomers: 3,
      ratingMasks: 5,
      ratingAccomodation: 3,
    },
    {
      name: "Cafe Olimpico",
      rating: 3,
      count: 128,
      location: "124 Rue Saint-Viateur O, Montreal, QC H2T 2L1",
      type: "cafe",
      business_id: 18,
      local: true,
      ratingSanitizer: 3,
      ratingSocialDistancing: 4,
      ratingLimitingCustomers: 5,
      ratingMasks: 2,
      ratingAccomodation: 1,
    },
    {
      name: "Sushi Momo Végétalien",
      rating: 5,
      count: 305,
      location: "3609 Rue Saint-Denis, Montreal, QC H2X 3L6",
      type: "restaurant",
      business_id: 19,
      local: true,
      ratingSanitizer: 5,
      ratingSocialDistancing: 4,
      ratingLimitingCustomers: 3,
      ratingMasks: 5,
      ratingAccomodation: 5,
    },
    {
      name: "Starbucks",
      rating: 3,
      count: 248,
      location: "3601 Boulevard Saint-Laurent, Montreal, QC H2X 2V5",
      type: "cafe",
      business_id: 20,
      local: false,
      ratingSanitizer: 5,
      ratingSocialDistancing: 3,
      ratingLimitingCustomers: 2,
      ratingMasks: 4,
      ratingAccomodation: 3,
    },
    {
      name: "Mae Sri",
      rating: 5, 
      count: 512,
      location: "224 Rue Milton, Montréal, QC H2X 1V6, Canada",
      type: "restaurant",
      business_id: 21,
      local: true,
      ratingSanitizer: 4,
      ratingSocialDistancing: 3,
      ratingLimitingCustomers: 5,
      ratingMasks: 3,
      ratingAccomodation: 5, 

    },
    {
      name: "Brigade Napolitaine",
      rating: 4, 
      count: 1200,
      location: "1428 Rue Stanley, Montréal, QC H3A 1P7, Canada",
      type: "restaurant",
      business_id: 22,
      local: true,
      ratingSanitizer: 4,
      ratingSocialDistancing: 4,
      ratingLimitingCustomers: 5,
      ratingMasks: 4,
      ratingAccomodation: 5, 
    },
    {
      name: "Carlos & Pepe's",
      rating: 3, 
      count: 1800,
      location: "1420 Rue Peel, Montréal, QC H3A 1S8, Canada",
      type: "restaurant",
      business_id: 23,
      local: true,
      ratingSanitizer: 4,
      ratingSocialDistancing: 3,
      ratingLimitingCustomers: 5,
      ratingMasks: 4,
      ratingAccomodation: 4, 
    },
    {
      name: "Lola Rosa",
      rating: 5, 
      count: 1400,
      location: "545 Rue Milton, Montréal, QC H2X 1W5, Canada",
      type: "restaurant",
      business_id: 24,
      local: true,
      ratingSanitizer: 5,
      ratingSocialDistancing: 3,
      ratingLimitingCustomers: 3,
      ratingMasks: 5,
      ratingAccomodation: 3, 
    },
    {
      name: "Tacos Tin Tan",
      rating: 4, 
      count: 456,
      location: "3828 R. Saint-Denis, Montréal, QC H2W 2M2, Canada",
      type: "restaurant",
      business_id: 25,
      local: true,
      ratingSanitizer: 4,
      ratingSocialDistancing: 3,
      ratingLimitingCustomers: 4,
      ratingMasks: 5,
      ratingAccomodation: 4, 
    },
    {
      name: "Bagels Etc",
      rating: 4,
      count: 612,
      location: "4320 Boul St-Laurent, Montréal, QC H2W 1Z3, Canada",
      type: "restaurant",
      business_id: 26,
      local: true,
      ratingSanitizer: 4,
      ratingSocialDistancing: 4,
      ratingLimitingCustomers: 3,
      ratingMasks: 4,
      ratingAccomodation: 4,
    },
    {
      name: "Cafe Santropol",
      rating: 4,
      count: 1322,
      location: "3990 Rue Saint-Urbain, Montréal, QC H2W 1T7, Canada",
      type: "restaurant",
      business_id: 27,
      local: true,
      ratingSanitizer: 5,
      ratingSocialDistancing: 5,
      ratingLimitingCustomers: 5,
      ratingMasks: 4,
      ratingAccomodation: 4,
    },
    {
      name: "Omnivor",
      rating: 4,
      count: 992,
      location: "4306 Boul St-Laurent, Montréal, QC H2W 1Z3, Canada",
      type: "restaurant",
      business_id: 28,
      local: true,
      ratingSanitizer: 4,
      ratingSocialDistancing: 3,
      ratingLimitingCustomers: 4,
      ratingMasks: 5,
      ratingAccomodation: 4,
    },
    {
      name: "Dirty Dogs",
      rating: 4,
      count: 1290,
      location: "3685 Boul St-Laurent, Montréal, QC H2X 2V5, Canada",
      type: "restaurant",
      business_id: 29,
      local: false,
      ratingSanitizer: 4,
      ratingSocialDistancing: 4,
      ratingLimitingCustomers: 4,
      ratingMasks: 3,
      ratingAccomodation: 5,
    },
    {
      name: "Les Deux Gamins",
      rating: 4,
      count: 340,
      location: "170 Rue Prince-Arthur E, Montréal, QC H2X 3B7, Canada",
      type: "restaurant",
      business_id: 30,
      local: true,
      ratingSanitizer: 4,
      ratingSocialDistancing: 4,
      ratingLimitingCustomers: 5,
      ratingMasks: 3,
      ratingAccomodation: 4,
    },
    {
      name: "Cafe St-Barth",
      rating: 5,
      count: 375,
      location: "3500 Av du Parc, Montréal, QC H2X 2H7, Canada",
      type: "cafe",
      business_id: 31,
      local: true,
      ratingSanitizer: 5,
      ratingSocialDistancing: 4,
      ratingLimitingCustomers: 4,
      ratingMasks: 5,
      ratingAccomodation: 4,
    },
    {
      name: "Cafe Nocturne",
      rating: 4,
      count: 355,
      location: "19 Rue Prince Arthur O, Montréal, QC H2X 1S4, Canada",
      type: "cafe",
      business_id: 32,
      local: true,
      ratingSanitizer: 3,
      ratingSocialDistancing: 4,
      ratingLimitingCustomers: 4,
      ratingMasks: 4,
      ratingAccomodation: 3,
    },
    {
      name: "Milton B",
      rating: 4,
      count: 780,
      location: " 3498 Av du Parc, Montréal, QC H2X 2H5, Canada",
      type: "cafe",
      business_id: 33,
      local: true,
      ratingSanitizer: 4,
      ratingSocialDistancing: 3,
      ratingLimitingCustomers: 4,
      ratingMasks: 3,
      ratingAccomodation: 4,
    },
    {
      name: "Juliette & Chocolat",
      rating: 4,
      count: 2031,
      location: "3600 Boul St-Laurent, Montréal, QC H2X 2V4, Canada",
      type: "cafe",
      business_id: 34,
      local: true,
      ratingSanitizer: 4,
      ratingSocialDistancing: 4,
      ratingLimitingCustomers: 5,
      ratingMasks: 5,
      ratingAccomodation: 4,
    },
    {
      name: "Le Darling",
      rating: 5,
      count: 1745,
      location: "4328 Boul St-Laurent, Montréal, QC H2W 1Z3, Canada",
      type: "bar",
      business_id: 35,
      local: true,
      ratingSanitizer: 4,
      ratingSocialDistancing: 3,
      ratingLimitingCustomers: 4,
      ratingMasks: 4,
      ratingAccomodation: 2,
    },
    {
      name: "La Petite Garconne",
      rating: 5,
      count: 1040,
      location: "3650 Boul St-Laurent, Montréal, QC H2X 2V4, Canada",
      type: "clothing store",
      business_id: 36,
      local: true,
      ratingSanitizer: 5,
      ratingSocialDistancing: 3,
      ratingLimitingCustomers: 4,
      ratingMasks: 5,
      ratingAccomodation: 4,
    },
    {
      name: "Eva B",
      rating: 4,
      count: 1365,
      location: "2015 Boul St-Laurent, Montréal, QC H2X 2T3, Canada",
      type: "clothing store",
      business_id: 37,
      local: true,
      ratingSanitizer: 5,
      ratingSocialDistancing: 4,
      ratingLimitingCustomers: 5,
      ratingMasks: 4,
      ratingAccomodation: 3,
    },
    {
      name: "Renaud Bray",
      rating: 4,
      count: 978,
      location: "4380 R. Saint-Denis, Montréal, QC H2J 2L1, Canada",
      type: "library",
      business_id: 38,
      local: false,
      ratingSanitizer: 4,
      ratingSocialDistancing: 5,
      ratingLimitingCustomers: 5,
      ratingMasks: 4,
      ratingAccomodation: 4,
    },
  ];

  const classes = useStyles();

  return (
    <div className={classes.root}>
      <GridList cellHeight={200} spacing={1} className={classes.gridList}>
        {businesses
          .filter(
            (business) =>
              business.name.toLowerCase().includes(filterValue.toLowerCase()) ||
              business.type.toLowerCase().includes(filterValue.toLowerCase()) ||
              business.rating.toString().includes(filterValue.toLowerCase())
          )
          .sort(
            (business1, business2) => {
            if (business1.rating > business2.rating)
              return -1;
            else if (business1.rating == business2.rating)
              return business2.count - business1.count;
            else 
              return 1;
            }

          )
          .map((business, i) => {
            return (
              <BusinessCard businessInfo={business} key={i}></BusinessCard>
            );
          })}
        ;
      </GridList>
    </div>
  );
};

export default AllBusiness;
